name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://npm.pkg.github.com/
      - run: bun install
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
