name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun build index.ts --outdir ./dist
      - name: Release
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm publish ./dist --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
